name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: ['12', '13', '14', '15', '16']

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run tests
        run: nix-shell --run "with-pg-${{ matrix.pg-version }} make installcheck"
      - if: ${{ failure() }}
        run: cat output/regression.diffs
